CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103154806_Init') THEN
    CREATE TABLE "Notes" (
        "ID" integer GENERATED BY DEFAULT AS IDENTITY,
        "Text" character varying(140),
        "Created" timestamp with time zone NOT NULL,
        "Update" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Notes" PRIMARY KEY ("ID")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103154806_Init') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260103154806_Init', '8.0.6');
    END IF;
END $EF$;
COMMIT;

